### ISSUE TITLE
Pathline missing translation to spatial reference coordinates

### ISSUE THREAD

**Issue by mjigmond** [modflowpy/flopy#151]
I just tested the write_shapefile() method of Pathline objects and it writes global coordinates straight from the pathline file without applying the xul/yul translation. Looking at src it appears that only the rotation property is being applied from the SpatialReference instance and xul/yul are missing.

In addition the k, i, j in the shapefile are totally wrong. By making some assumptions it seems that:
- k = layer-1
- i = row-1
- j = layer-1

There's virtually no reason for k == j.

**Comment by aleaf** [comment]
this should be addressed by pull request <https://github.com/modflowpy/flopy/pull/152>

**Comment by langevin-usgs** [comment]
@mjigmond, this should hopefully be fixed by @aleaf.  Can you test it with your problem?

**Comment by mjigmond** [comment]
Not quite. #152 fixes the **x** translation but **y** ends up outside the model domain (remember MP offset is LLC vs Flopy's ULC). Also, the k/i/j is only partially fixed. Expected 4/525/284 and received 4/525/4. Is j replaced by k at write time?

**Comment by aleaf** [comment]
@mjigmond, can you post an example that reproduces your problem? These issues should be covered by the ```get_destination_data``` test in ```autotests/t031_test.py```. If you run that test, it will export shapefiles of the endpoints, pathlines and dis package, which can be compared in a GIS GUI. I'm not seeing any of these issues in the test output.

**Comment by mjigmond** [comment]
I will try to generate a small subset but meanwhile there's at least one issue with that test:
1. There's no **assert** test for **j** so if you open up pathlines_1per.shp you'll notice **j** is inconsistent with **j** from pathlines.shp and starting_locs.shp.

The reason my test problem could be failing is because I am not using model SR (m.sr) but rather create a PathlineFile object that I then try to export as in (which should work nonetheless):
```
xul=3628793
yul=21940389
pthobj = flopy.utils.PathlineFile(somepathlineFile)
pthobj.write_shapefile(shpname='test.shp', sr=flopy.utils.reference.SpatialReference(delr=2.640000E+03, delc=2.640000E+03, lenuni=1, xul=xul, yul=yul, rotation=0.0))
```
Just for kicks I replaced yul with the value of yll and the result is almost as expected, it's off by a full row. That tells me there's something wrong with the handling of the origin, where for model definition you use UL and MODPATH uses a LL.

**Comment by aleaf** [comment]
@mjigmond,
the k=j issue in the export of single geometry pathlines should be fixed by https://github.com/modflowpy/flopy/pull/154  (was a typo).

to your second issue- the use of an sr object not attached to the model is fine (it is just another instance, and I don't believe that ```SpatialReference``` has any hooks back to a model instance). 

However because of this, and because ```SpatialReference``` performs rotations on the lower left corner of the grid, but offsets on the upper right corner, it currently cannot transform an arbitrary set of coordinates without knowledge of length of the y-dimension of the model grid. For transformations that are consistent with the grid, the user currently has to supply delr and delc as 1D arrays (equivalent to m.dis.delr and m.dis.delc).

This should probably be fixed so that SR is agnostic about what it is transforming (i.e., it would just perform a rotation, scaling and offset independent of the model grid), but this would require some refactoring of the SR class. It is my understanding that the current configuration is meant to follow the matrix (and MODFLOW) convention of an origin in the upper right corner. However it seems like it would be simpler (and more consistent with GIS conventions) to work entirely off the lower left corner (while allowing users to specify a separate origin or rotation if they really want).

@jtwhite79- do you have any comments?

**Comment by aleaf** [comment]
to clarify, SR takes xul, yul and converts to the lower left corner to perform the transformation (```self.yedge[0]``` is the distance along the axis to the lower left corner):
```
    def transform(self, x, y):
        """
        Given x and y array-like values, apply rotation, scale and offset,
        to convert them from model coordinates to real-world coordinates.
        """
        x, y = SpatialReference.rotate(x * self.length_multiplier,
                                       y * self.length_multiplier,
                                       theta=self.rotation,
                                       xorigin=0, yorigin=self.yedge[0])
        x += self.xul
        y += self.yul - self.yedge[0]
```
the problem is that it doesn't know the correct ```self.yedge[0]``` unless the grid spacings are supplied.

**Comment by mjigmond** [comment]
Thanks. I followed your advice and specified the delr/delc properties of SpatialReference as 1D arrays and that fixes the issue. Using the model SR (m.dis.delr) you're guaranteed a 1D array otherwise you need to be aware of the SpatialReference limitation.

I'll make a suggestion as to the SpatialReference implementation. Should SpatialReference be self-sufficient? That is, should it contain the (nrow,ncol) dimension (or (nlay,nrow,ncol)) so that it could be used without a model instance or guessing?

**Comment by aleaf** [comment]
just submitted a pull request that implements a lower left input option for SpatialReference. See https://github.com/modflowpy/flopy/pull/155. It should be able to be used now without a reference to the model grid (as long as lower left x, y is supplied).

**Comment by mjigmond** [comment]
Just tested the patch and it needs some fixes. The delr/delc sequences need to be converted to NumPy arrays before delr.sum().

```
  File "C:\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\flopy\utils\reference.py", line 99, in __init__
    if delr.sum() == 0 or delc.sum() == 0:
AttributeError: 'list' object has no attribute 'sum'
```
